NetflixBlog/Controllers/PostsController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using NetflixBlog.Data;
using NetflixBlog.Models;
using ActionResult = Microsoft.AspNetCore.Mvc.ActionResult;
using Controller = Microsoft.AspNetCore.Mvc.Controller;
using SelectListItem = Microsoft.AspNetCore.Mvc.Rendering.SelectListItem;

namespace NetflixBlog.Controllers
{
    [Microsoft.AspNetCore.Authorization.Authorize(Roles = "Client, Admin")]
    public class PostsController : Controller
    {
        private readonly NetflixBlogContext _context;

        public PostsController(NetflixBlogContext context)
        {
            _context = context;
        }


        // GET: Posts
        public async Task<ActionResult> Index()
        {
            return View(await _context.Post.ToListAsync());
        }

        // GET: Posts/Details/5
        public ActionResult Details(int? id, int? series)
        {
            if (id == null)
            {
                return BadRequest();
            }
            Post post = _context.Post.Find(id);
            if (post == null)
            {
                return NotFound();
            }
            return View(post);
        }

        // GET: Posts/Create
        public ActionResult Create()
        {
            //var allSeries = _context.Series;
            ////this.ViewData["seriesSelectable"] = (IEnumerable<Models.Series>)allSeries;

            //var allPosts = _context.Post;
            //PostCreation pc = new PostCreation();
            ////pc.SeriesNamesList = allSeries;

            //foreach (var series in allSeries)
            //{
            //    //pc.SeriesNamesList.Add(series.Name); 
            //    pc.Series.Add(series);
            //}

            //this.ViewData["seriesSelectable"] = (IEnumerable<PostCreation>) pc;
            // this.ViewData["Create"] = pc;


            List<SelectListItem> series = new List<SelectListItem>();

            // Build the select list of all the possible Series
            foreach (Series series1 in _context.Series.ToList())
            {
                series.Add(new SelectListItem { Text = series1.Name, Value = series1.SeriesID.ToString() });
            }

            ViewBag.Series = series;

            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Microsoft.AspNetCore.Mvc.HttpPost]
        [Microsoft.AspNetCore.Mvc.ValidateAntiForgeryToken]
        public ActionResult Create([Microsoft.AspNetCore.Mvc.Bind("PostID,Title,AuthorName,SeriesID,Content")] Post post, string category, string Series)
        {
            post.Date = DateTime.Now;
            if (ModelState.IsValid)
            {
                Category newCategory;
                //if (string.IsNullOrEmpty(category) && string.IsNullOrEmpty(Series))
                //{
                //    _context.Post.Add(post);
                //    _context.SaveChanges();

                //    return View(post);

                //}
                //else
                //  {
                if (!string.IsNullOrEmpty(category))
                {
                    Enum.TryParse(category, out newCategory);
                    post.Category = newCategory;
                }

                if (!string.IsNullOrEmpty(Series))
                {
                    post.SeriesId = Int32.Parse(Series);
                    //var series = _context.Series.Where(s => s.SeriesID == seriesID);
                }

                _context.Post.Add(post);
                _context.SaveChanges();

                int prediction;
                int.TryParse(category, out prediction);

                return RedirectToAction("Index");
                // }
            }

            var allSeries = _context.Series;
            this.ViewData["seriesSelectable"] = (IEnumerable<Models.Series>)allSeries;
            return View(post);
        }

        public ActionResult Approve(int? id, Category category)
        {
            Post post = _context.Post.Find(id);
            _context.Entry(post).State = EntityState.Modified;
            post.Category = category;
            _context.SaveChanges();

            int prediction;
            int.TryParse(category.GetHashCode().ToString(), out prediction);

            return RedirectToAction("Index");
        }

        [Microsoft.AspNetCore.Mvc.HttpPost]
        [Microsoft.AspNetCore.Mvc.ValidateAntiForgeryToken]
        public ActionResult Suggestion([Microsoft.AspNetCore.Mvc.Bind("PostID")] int? PostID, string category)
        {
            Category newCategory;

            if (!string.IsNullOrEmpty(category) && Enum.TryParse(category, out newCategory))
            {
                Approve(PostID, newCategory);
            }

            return RedirectToAction("Index");
        }

        // GET: Posts/Edit/5
        [Microsoft.AspNetCore.Authorization.Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            Post post = _context.Post.Find(id);
            if (post == null)
            {
                return NotFound();
            }

            var allSeries = _context.Series;
            this.ViewData["seriesSelectable"] = (IEnumerable<Models.Series>)allSeries;

            List<SelectListItem> series = new List<SelectListItem>();

            // Build the select list of all the possible Series
            foreach (Series series1 in allSeries.ToList())
            {
                series.Add(new SelectListItem { Text = series1.Name, Value = series1.SeriesID.ToString() });
            }

            ViewBag.Series = series;


            return View(post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Microsoft.AspNetCore.Mvc.HttpPost]
        [Microsoft.AspNetCore.Mvc.ValidateAntiForgeryToken]
        public ActionResult Edit([Microsoft.AspNetCore.Mvc.Bind("PostID,Title,AuthorName,SeriesID,Series,Date,Content")] Post post, string category, string Series)
        {
            if (ModelState.IsValid)
            {
                _context.Entry(post).State = EntityState.Modified;
                Category newCategory;
                Enum.TryParse(category, out newCategory);
                post.Category = newCategory;
                post.SeriesId = Int32.Parse(Series);
                _context.Entry(post).State = EntityState.Modified;
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            var allSeries = _context.Series;
            this.ViewData["seriesSelectable"] = (IEnumerable<Models.Series>)allSeries;
            return View(post);
        }

        // GET: Posts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            Post post = _context.Post.Find(id);
            if (post == null)
            {
                return NotFound();
            }
            return View(post);
        }

        // POST: Posts/Delete/5
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.ActionName("Delete")]
        [Microsoft.AspNetCore.Mvc.ValidateAntiForgeryToken]
        [Microsoft.AspNetCore.Authorization.Authorize(Roles = "Admin")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Post post = await _context.Post.FindAsync(id);
            _context.Post.Remove(post);
            IQueryable<Comment> comments =  _context.Comment.Where(c => c.PostID == id);
            foreach (var c in comments)
            {
                _context.Comment.Remove(c);
            }
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Posts
        public ActionResult Filter(string seriesGenre, string authorName, string seriesName, string postCategory)
        {
            // var results = _context.Post.AsQueryable();
            var results = _context.Post.Include(p => p.Series).AsQueryable();
            Genre genre;
            Category category;
            if (!string.IsNullOrEmpty(seriesName))
            {
                results = _context.Post
                    .Join(_context.Series, post => post.SeriesId, series => series.SeriesID,
                        (post, series) => new { post, series })
                    .Where(@p => @p.series.Name == seriesName)
                    .Select(@t => @t.post);
            }
            if (!string.IsNullOrEmpty(authorName))
            {
                results = results.Where(p => p.AuthorName.Contains(authorName));
            }
            if (!string.IsNullOrEmpty(postCategory) && Enum.TryParse(postCategory, out category))
            {
                results = results.Where(m => m.Category == category);
            }
            return View("Filter", results.ToList());
        }

        public async Task<ActionResult> GroupBySeries()
        {
            // Group by and join
            //IQueryable<SelectBySeries> postsAmount = _context.Post.GroupBy(post => post.SeriesId)
            //    .Join(_context.Series, g => g.Key, series => series.SeriesID,
            //        (g, series) => new SelectBySeries() { SeriesName = series.Name, PostsAmount = g.Sum(m => 1) });

           

            //var source = _context.Post
            //    .Select(m => new
            //    {
            //        Key = new

NetflixBlog/Controllers/TwitterController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Tweetinvi.Models;
using System;
using Tweetinvi;
using NetflixBlog.Models;

namespace NetflixBlog.Controllers
{
    [Authorize(Roles = "Client, Admin")]
    public class TwitterController : Controller
    {
        private const string TWITTER_CONSUMER_ID = "AVd5RrV0QpDClKkGdz9J9F6Nm";
        private const string TWITTER_CONSUMER_SECRET = "0CoQOMKgs8fb4jhFPVlMGELE07vpiiD80kGYKTZM1OKYkReRgO";
        private const string TWITTER_ACCESS_TOKEN = "1429534747890536448-cHJePwbFDErIUy9NMG1DFkVn9HEiGf";
        private const string TWITTER_ACCESS_TOKEN_SECRET = "oTAvcC6OmQ31Cr9LoNoDWR3FlcNMT0JOjB8rKqVARlGnU";

        // GET: Twitter/Tweet
        public ActionResult Create()
        {
            return View();
        }

        // POST Twitter/Tweet
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(Tweet tweet)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var userClient = new TwitterClient(TWITTER_CONSUMER_ID, TWITTER_CONSUMER_SECRET, TWITTER_ACCESS_TOKEN, TWITTER_ACCESS_TOKEN_SECRET);

                    // Publish a tweet
                    var publishedTweet = await userClient.Tweets.PublishTweetAsync(tweet.TweetText);
                }
                catch (Exception ex)
                {
                    ViewBag.Error = "Something went wrong, please try again";
                }
            }

            return View();
        }
    }
}

NetflixBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NetflixBlog</title>
    <link rel="shortcut icon" href="~/netflix_icon.ico" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/home_page.css" type="text/css" />
    <link rel="stylesheet" href="~/css/about.css" type="text/css" />
    <link rel="stylesheet" href="~/css/admin_login.css" type="text/css" />
    <link rel="stylesheet" href="~/css/register.css" type="text/css" />
    <link rel="stylesheet" href="~/css/trailer.css" type="text/css" />

</head>

<body>
    <header>
        <div class="blog-app-bar">
            <h6 class="blog-title">
                <div id="imageWrapper">
                    <img class="netflixPic" src="~/images/Netflix.png" width="130" /> @Html.ActionLink("Blog", "Index",
                    "Posts")
                </div>
            </h6>
            <div style="width: 90%">
                <nav class="nav" style="width:100%">
                    <!-- Navigation -->
                    <ul>
                        <li class="nav-link">@Html.ActionLink("Series", "Index", "Series")</li>
                        <li class="nav-link">@Html.ActionLink("Posts", "Filter", "Posts")</li>
                        <li class="nav-link">@Html.ActionLink("Locations", "Locations", "Series")</li>
                        <li class="nav-link">@Html.ActionLink("About", "About", "Home")</li>
                        @if (Context.User != null && Context.User.Claims != null && Context.User.IsInRole("Admin"))
                        {
                            <li class="nav-link">@Html.ActionLink("Users", "Index", "Users")</li>
                            <li class="nav-link">@Html.ActionLink("Actors", "Index", "Actors")</li>
                        }
                        @if (Context.User != null && Context.User.Claims != null && Context.User.Claims.Count() > 0)
                        {
                            <li class="nav-link dropdown options-dropdown">
                                <button class="dropbtn options-btn">Options</button>
                                <ul class="dropdown-content">
                                    <li class="nav-link">@Html.ActionLink("Comments", "Index", "Comments")</li>
                                    <li class="nav-link">@Html.ActionLink("Tweet", "Create", "Twitter")</li>
                                    <li class="nav-link">@Html.ActionLink("Logout", "Logout", "Users")</li>
                                </ul>
                            </li>

                        }
                        else
                        {
                            <li class="nav-link">@Html.ActionLink("Login", "Login", "Users")</li>
                        }

                    </ul>
                </nav>
            </div>
        </div>
    </header>

    <main role="main" class="main-background">
        <aside class="col-sm-2 aside">
            <div class="sidebar-module">
                <ul>
                    <li class="nav-link">@Html.ActionLink("Series", "Index", "Series")</li>
                    <li class="nav-link">@Html.ActionLink("Posts", "Filter", "Posts")</li>
                    <li class="nav-link">@Html.ActionLink("Locations", "Locations", "Series")</li>
                    <li class="nav-link">@Html.ActionLink("About", "About", "Home")</li>
                </ul>
            </div>
        </aside>

        <div class="container" style="width:80%;">
            <div class="col-sm-12 blog-main">
                @RenderBody()
            </div>
        </div>
    </main>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - NetflixBlog - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>